### ISSUE TITLE
Figuras no tienen un alt

### ISSUE THREAD

**Issue by devferx** [scesi/scesi-website#16]

**Comment by diegodev-01** [comment]
problem solved, please check my pull request

**Comment by devferx** [comment]
Good job
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWI3MXRoYnl5YzN1NnBiODc2OGkwa2ZrMW9wOHRwaTh1ZThuY29lMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HzPtbOKyBoBFsK4hyc/giphy.gifhttps://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWI3MXRoYnl5YzN1NnBiODc2OGkwa2ZrMW9wOHRwaTh1ZThuY29lMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HzPtbOKyBoBFsK4hyc/giphy.gif)
